#!/bin/bash
# 
# Installation script which setup an Ubuntu Xenial machine to use this
# xmonad configuration. 
#
# WARNING!!! 
# * This has only been tested on a limited number of machines running 
#   Ubuntu 16.04 64-bit.
# * This is not a sophisticated installation script by any stretch 
#   of the imagination. 
# * I take no responsibility if this overwrites any configuration settings 
#   or otherwise messes up your system. 
#
# Please review the readme file to find out exactly what it does and does not 
# do. Or, visit the repository for more information: 
# https://github.com/davidbrewer/xmonad-ubuntu-conf
# 
# Author: David Brewer
# Updates: Graham Holland

echo "Installing prerequisite libraries..."
sudo apt-get install libx11-dev libxinerama-dev libxext-dev libxpm-dev libxrandr-dev libxft-dev libasound2-dev c2hs

echo "Installing Haskell packages..."
sudo apt-get install ghc cabal-install

echo "Install xmonad and xmobar through cabal..."
cabal update
cabal install xmonad
cabal install xmonad-contrib
cabal install xmobar -f with_xft -f with_alsa

echo "Installing extra packages..."
sudo apt-get install xcompmgr nitrogen stalonetray moreutils consolekit synapse
acpi redshift lxappearance rxvt-unicode

echo "Creating xmonad xsession configuration..."
sudo mv /usr/share/xsessions/xmonad.desktop /usr/share/xsessions/xmonad.desktop.original
sudo cp ~/.xmonad/xmonad.desktop /usr/share/xsessions
sudo chmod a+r /usr/share/xsessions/xmonad.desktop
sudo cp ~/.xmonad/images/custom_xmonad_badge.png /usr/share/unity-greeter
sudo chmod a+r /usr/share/unity-greeter/custom_xmonad_badge.png

echo "Linking to customized gnome 2 configuration..."
mv ~/.gtkrc-2.0 ~/.gtkrc-2.0.original
ln -s .xmonad/.gtkrc-2.0 ~/.gtkrc-2.0

